apiVersion: v1
kind: Pod
metadata:
  name: my-web-pod
spec:
  containers:
    - name: my-web-container
      image: nginx:latest # Пример образа веб-сервера Nginx
      ports:
        - containerPort: 80
